# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'MovieMate' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MovieMate
  pod 'AFNetworking'

  target 'MovieMateTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MovieMateUITests' do
    # Pods for testing
  end

end
